# -*- coding: utf-8 -*-
"""Chinese translations for Heroes of Might and Magic 3 Savegame Editor.

This module provides Chinese translations for game UI elements.
Import this module and call set_chinese() to enable Chinese labels.
"""

import sys
import os

_zh_translations = {}

def _merge_ordereddict(original, translations):
    """Merge translations into an OrderedDict."""
    from collections import OrderedDict
    result = OrderedDict()
    for key, value in original.items():
        # For PRIMARY_ATTRIBUTES, value is the English label, which is the key in translations
        if value in translations:
            result[key] = translations[value]
        elif key in translations:
            result[key] = translations[key]
        else:
            result[key] = value
    return result

def _translate_list(original_list, translations):
    """Translate items in a list if translations exist."""
    return [translations.get(item, item) for item in original_list]

def _translate_dict(original_dict, translations):
    """Translate values in a dictionary if translations exist."""
    result = {}
    for key, value in original_dict.items():
        if value in translations:
            result[key] = translations[value]
        elif key in translations:
            result[key] = translations[key]
        else:
            result[key] = value
    return result

def set_chinese():
    """Apply Chinese translations to h3sed.metadata module."""
    global _zh_translations

    _zh_translations = {
        "Attack": "攻击力",
        "Defense": "防御力",
        "Spell Power": "法术攻击力",
        "Knowledge": "法术防御力",
        "Basic": "基础",
        "Advanced": "高级",
        "Expert": "专家",
        "Red": "红色",
        "Blue": "蓝色",
        "Tan": "棕色",
        "Green": "绿色",
        "Orange": "橙色",
        "Purple": "紫色",
        "Teal": "青色",
        "Pink": "粉色",
    }

    skill_translations = {
        "Pathfinding": "寻路术",
        "Archery": "箭术",
        "Logistics": "后勤学",
        "Scouting": "侦察术",
        "Diplomacy": "外交术",
        "Navigation": "航海术",
        "Leadership": "领导力",
        "Wisdom": "智慧",
        "Mysticism": "神秘术",
        "Luck": "幸运术",
        "Ballistics": "弹道学",
        "Eagle Eye": "鹰眼",
        "Necromancy": "招魂术",
        "Estates": "理财术",
        "Fire Magic": "火魔法",
        "Air Magic": "气魔法",
        "Water Magic": "水魔法",
        "Earth Magic": "土魔法",
        "Scholar": "学者",
        "Tactics": "战术",
        "Artillery": "炮术",
        "Learning": "学习",
        "Offense": "进攻",
        "Armorer": "装甲术",
        "Intelligence": "智力",
        "Sorcery": "魔法",
        "Resistance": "抗魔",
        "First Aid": "急救",
    }
    _zh_translations.update(skill_translations)

    special_artifact_translations = {
        "Ammo Cart": "弹药车",
        "Ballista": "弩车",
        "Catapult": "投石车",
        "First Aid Tent": "急救帐篷",
        "Spellbook": "法术书",
    }
    _zh_translations.update(special_artifact_translations)

    creature_translations = {
        "Air Elemental": "气元素",
        "Ancient Behemoth": "远古巨兽",
        "Angel": "天使",
        "Arch Devil": "大恶魔",
        "Arch Mage": "大法师",
        "Archangel": "大天使",
        "Archer": "弓箭手",
        "Basilisk": "蜥怪",
        "Battle Dwarf": "战斗矮人",
        "Behemoth": "巨兽",
        "Beholder": "眼魔",
        "Black Dragon": "黑龙",
        "Black Knight": "黑骑士",
        "Bone Dragon": "骨龙",
        "Cavalier": "骑士",
        "Centaur": "半人马",
        "Centaur Captain": "半人马首领",
        "Cerberus": "地狱犬",
        "Champion": "冠军骑士",
        "Chaos Hydra": "混沌九头蛇",
        "Crusader": "十字军",
        "Cyclops": "独眼巨人",
        "Cyclops King": "独眼巨人王",
        "Demon": "恶魔",
        "Dread Knight": "恐怖骑士",
        "Dendroid Guard": "树妖守卫",
        "Dendroid Soldier": "树妖战士",
        "Devil": "恶魔",
        "Diamond Golem": "钻石傀儡",
        "Dragon Fly": "蜻蜓",
        "Dwarf": "矮人",
        "Earth Elemental": "土元素",
        "Efreeti": "火精灵",
        "Efreet Sultan": "火精灵苏丹",
        "Evil Eye": "邪眼",
        "Familiar": "魔宠",
        "Fire Elemental": "火元素",
        "Genie": "灯神",
        "Ghost Dragon": "幽灵龙",
        "Giant": "巨人",
        "Gnoll": "豺狼人",
        "Gnoll Marauder": "豺狼人掠夺者",
        "Goblin": "哥布林",
        "Gog": "烈火精灵",
        "Gold Dragon": "金龙",
        "Gold Golem": "黄金傀儡",
        "Gorgon": "蛇发女妖",
        "Grand Elf": "大精灵",
        "Greater Basilisk": "巨型蜥怪",
        "Green Dragon": "绿龙",
        "Gremlin": "小妖精",
        "Griffin": "狮鹫",
        "Halberdier": "戟兵",
        "Harpy": "鹰身女妖",
        "Harpy Hag": "鹰身女巫",
        "Hell Hound": "地狱猎犬",
        "Hobgoblin": " hobgoblin",
        "Horned Demon": "角魔",
        "Hydra": "九头蛇",
        "Imp": "小魔鬼",
        "Infernal Troglodyte": "地狱洞穴人",
        "Iron Golem": "铁傀儡",
        "Lich": "巫妖",
        "Lizard Warrior": "蜥蜴战士",
        "Lizardman": "蜥蜴人",
        "Mage": "魔法师",
        "Magog": "烈火精灵王",
        "Manticore": "蝎尾狮",
        "Marksman": "神射手",
        "Master Genie": "灯神大师",
        "Master Gremlin": "高级小妖精",
        "Medusa": "美杜莎",
        "Medusa Queen": "美杜莎女王",
        "Mighty Gorgon": "强力蛇发女妖",
        "Minotaur": "牛头人",
        "Minotaur King": "牛头人王",
        "Monk": "僧侣",
        "Naga": "娜迦",
        "Naga Queen": "娜迦女王",
        "Obsidian Gargoyle": "黑曜石石像鬼",
        "Ogre": "食人魔",
        "Ogre Mage": "食人魔法师",
        "Orc": "兽人",
        "Orc Chieftain": "兽人酋长",
        "Pegasus": "飞马",
        "Pikeman": "枪兵",
        "Pit Fiend": "深渊恶魔",
        "Pit Lord": "深渊领主",
        "Power Lich": "强力巫妖",
        "Red Dragon": "红龙",
        "Roc": "巨鹏",
        "Royal Griffin": "皇家狮鹫",
        "Scorpicore": "蝎狮",
        "Serpent Fly": "蛇蝇",
        "Silver Pegasus": "银飞马",
        "Skeleton": "骷髅",
        "Skeleton Warrior": "骷髅战士",
        "Stone Gargoyle": "石像鬼",
        "Stone Golem": "石傀儡",
        "Swordsman": "剑士",
        "Zealot": "狂热者",
        "Zombie": "僵尸",
        "Thunderbird": "雷鸟",
        "Titan": "泰坦",
        "Troglodyte": "洞穴人",
        "Unicorn": "独角兽",
        "Walking Dead": "行尸",
        "Vampire": "吸血鬼",
        "Vampire Lord": "吸血鬼王",
        "War Unicorn": "战争独角兽",
        "Water Elemental": "水元素",
        "Wight": "尸巫",
        "Wolf Raider": "狼骑兵",
        "Wolf Rider": "狼骑士",
        "Wood Elf": "木精灵",
        "Wraith": "怨灵",
        "Wyvern": "双足飞龙",
        "Wyvern Monarch": "双足飞龙王",
    }
    _zh_translations.update(creature_translations)

    spell_translations = {
        "Air Shield": "气盾",
        "Animate Dead": "复活死尸",
        "Anti-Magic": "抗魔",
        "Armageddon": "世界末日",
        "Berserk": "疯狂",
        "Bless": "祝福",
        "Blind": "失明",
        "Bloodlust": "嗜血",
        "Chain Lightning": "连锁闪电",
        "Clone": "镜像",
        "Counterstrike": "反击",
        "Cure": "治疗",
        "Curse": "诅咒",
        "Death Ripple": "死亡波纹",
        "Destroy Undead": "灭亡灵",
        "Dimension Door": "次元门",
        "Disguise": "伪装",
        "Dispel": "驱散",
        "Disrupting Ray": "瓦解射线",
        "Earthquake": "地震",
        "Fire Shield": "火盾",
        "Fire Wall": "火墙",
        "Fireball": "火球术",
        "Fly": "飞行",
        "Force Field": "力场",
        "Forgetfulness": "遗忘",
        "Fortune": "幸运",
        "Frenzy": " frenzy",
        "Frost Ring": " frost ring",
        "Haste": "加速",
        "Hypnotize": "催眠",
        "Ice Bolt": "冰箭",
        "Implosion": "内爆",
        "Inferno": "地狱火",
        "Land Mine": "地雷",
        "Lightning Bolt": "闪电",
        "Magic Arrow": "魔法箭",
        "Magic Mirror": "魔镜",
        "Meteor Shower": "流星雨",
        "Mirth": "欢乐",
        "Misfortune": "不幸",
        "Prayer": "祈祷",
        "Precision": "精准",
        "Protection from Air": "气系防护",
        "Protection from Earth": "土系防护",
        "Protection from Fire": "火系防护",
        "Protection from Water": "水系防护",
        "Quicksand": "流沙",
        "Remove Obstacle": "清除障碍",
        "Resurrection": "复活",
        "Sacrifice": "牺牲",
        "Scuttle Boat": "沉船",
        "Shield": "盾牌",
        "Slayer": "屠宰",
        "Slow": "减速",
        "Sorrow": "悲伤",
        "Stone Skin": "石肤",
        "Summon Air Elemental": "召唤气元素",
        "Summon Boat": "召唤船只",
        "Summon Earth Elemental": "召唤土元素",
        "Summon Fire Elemental": "召唤火元素",
        "Summon Water Elemental": "召唤水元素",
        "Teleport": "传送",
        "Town Portal": "回城术",
        "Water Walk": "水上行走",
        "Weakness": "虚弱",
        "View Air": "探气",
        "View Earth": "探地",
        "Visions": "幻象",
    }
    _zh_translations.update(spell_translations)

    artifact_translations = {
        "Ambassador's Sash": "大使绶带",
        "Amulet of the Undertaker": "亡灵护身符",
        "Angel Feather Arrows": "天使羽毛箭",
        "Angel Wings": "天使翅膀",
        "Armor of Wonder": "奇迹盔甲",
        "Arms of Legion": "军团之臂",
        "Badge of Courage": "勇气徽章",
        "Bird of Perception": "感知之鸟",
        "Blackshard of the Dead Knight": "死亡骑士的黑shard",
        "Boots of Levitation": "悬浮靴",
        "Boots of Polarity": "极性靴",
        "Boots of Speed": "速度靴",
        "Bow of Elven Cherrywood": "精灵樱桃木弓",
        "Bowstring of the Unicorn's Mane": "独角兽鬃毛弓弦",
        "Breastplate of Brimstone": "硫磺胸甲",
        "Breastplate of Petrified Wood": "石化木胸甲",
        "Buckler of the Gnoll King": "豺狼人王的圆盾",
        "Cape of Conjuring": "召唤披风",
        "Cape of Velocity": "速度披风",
        "Cards of Prophecy": "预言卡片",
        "Celestial Necklace of Bliss": "天堂祝福项链",
        "Centaur's Axe": "半人马战斧",
        "Charm of Mana": "魔力 charm",
        "Clover of Fortune": "幸运三叶草",
        "Collar of Conjuring": "召唤项圈",
        "Crest of Valor": "勇气纹章",
        "Crown of Dragontooth": "龙牙王冠",
        "Crown of the Supreme Magi": "大魔法师王冠",
        "Dead Man's Boots": "死人靴",
        "Diplomat's Ring": "外交官戒指",
        "Dragon Scale Armor": "龙鳞盔甲",
        "Dragon Scale Shield": "龙鳞盾牌",
        "Dragon Wing Tabard": "龙翼战袍",
        "Dragonbone Greaves": "龙骨护胫",
        "Emblem of Cognizance": "认知纹章",
        "Endless Bag of Gold": "无尽金币袋",
        "Endless Purse of Gold": "无尽金币钱包",
        "Endless Sack of Gold": "无尽金币袋",
        "Equestrian's Gloves": "骑手手套",
        "Everflowing Crystal Cloak": "永流水晶披风",
        "Everpouring Vial of Mercury": "永流水银瓶",
        "Eversmoking Ring of Sulfur": "永烟硫磺戒指",
        "Garniture of Interference": "干扰装饰",
        "Glyph of Gallantry": "英勇印记",
        "Golden Bow": "黄金弓",
        "Greater Gnoll's Flail": "大豺狼人的链枷",
        "Head of Legion": "军团之首",
        "Hellstorm Helmet": "地狱风暴头盔",
        "Helm of Chaos": "混沌头盔",
        "Helm of Heavenly Enlightenment": "天堂启示头盔",
        "Helm of the Alabaster Unicorn": "雪花独角兽头盔",
        "Hourglass of the Evil Hour": "邪恶时刻沙漏",
        "Inexhaustible Cart of Lumber": "无尽木材车",
        "Inexhaustible Cart of Ore": "无尽矿石车",
        "Ladybird of Luck": "幸运瓢虫",
        "Legs of Legion": "军团之腿",
        "Lion's Shield of Courage": "狮子勇气盾牌",
        "Loins of Legion": "军团之腰",
        "Mystic Orb of Mana": "神秘魔力球",
        "Necklace of Dragonteeth": "龙牙项链",
        "Necklace of Ocean Guidance": "海洋指引项链",
        "Necklace of Swiftness": "迅捷项链",
        "Ogre's Club of Havoc": "食人魔的破坏棍棒",
        "Orb of Driving Rain": "暴雨球",
        "Orb of the Firmament": "苍穹球",
        "Orb of Inhibition": "抑制球",
        "Orb of Silt": "淤泥球",
        "Orb of Tempestuous Fire": "狂暴火球",
        "Orb of Vulnerability": "弱点球",
        "Pendant of Courage": "勇气 pendant",
        "Pendant of Death": "死亡 pendant",
        "Pendant of Dispassion": "冷静 pendant",
        "Pendant of Free Will": "自由意志 pendant",
        "Pendant of Holiness": "圣洁 pendant",
        "Pendant of Life": "生命 pendant",
        "Pendant of Negativity": "负面 pendant",
        "Pendant of Second Sight": "第二视觉 pendant",
        "Pendant of Total Recall": "完全回忆 pendant",
        "Quiet Eye of the Dragon": "龙的平静之眼",
        "Recanter's Cloak": " recanter's 披风",
        "Red Dragon Flame Tongue": "红龙火焰舌",
        "Rib Cage": "肋骨笼",
        "Ring of Conjuring": "召唤戒指",
        "Ring of Infinite Gems": "无尽宝石戒指",
        "Ring of Life": "生命戒指",
        "Ring of the Wayfarer": "旅行者戒指",
        "Ring of Vitality": "活力戒指",
        "Sandals of the Saint": "圣徒凉鞋",
        "Scales of the Greater Basilisk": "巨型蜥怪的鳞片",
        "Sea Captain's Hat": "船长帽",
        "Sentinel's Shield": "哨兵盾牌",
        "Shackles of War": "战争枷锁",
        "Shield of the Damned": "诅咒盾牌",
        "Shield of the Dwarven Lords": "矮人领主盾牌",
        "Shield of the Yawning Dead": "哈欠亡灵盾牌",
        "Skull Helmet": "骷髅头盔",
        "Speculum": " speculum",
        "Spellbinder's Hat": "缚法者帽",
        "Sphere of Permanence": "永恒球体",
        "Spirit of Oppression": "压迫之灵",
        "Spyglass": "望远镜",
        "Statesman's Medal": "政治家勋章",
        "Still Eye of the Dragon": "龙的静止之眼",
        "Stoic Watchman": " stoic 守望者",
        "Surcoat of Counterpoise": "平衡外袍",
        "Sword of Hellfire": "地狱火剑",
        "Sword of Judgement": "审判之剑",
        "Talisman of Mana": "魔力 talisman",
        "Targ of the Rampaging Ogre": "狂暴食人魔的 targ",
        "Thunder Helmet": "雷霆头盔",
        "Titan's Cuirass": "泰坦胸甲",
        "Titan's Gladius": "泰坦剑",
        "Tome of Air": "气系法术书",
        "Tome of Earth": "土系法术书",
        "Tome of Fire": "火系法术书",
        "Tome of Water": "水系法术书",
        "Torso of Legion": "军团之躯干",
        "Tunic of the Cyclops King": "独眼巨人王的束腰外衣",
        "Vampire's Cowl": "吸血鬼斗篷",
        "Vial of Lifeblood": "生命血瓶",
    }
    _zh_translations.update(artifact_translations)

    # 更新导出的翻译字典
    PRIMARY_ATTRIBUTES = _zh_translations
    SKILLS = skill_translations
    SPELLS = spell_translations
    CREATURES = creature_translations
    ARTIFACTS = artifact_translations
    ARTIFACTS.update(special_artifact_translations)

    return True

def get_translations():
    """Return the current translations dictionary."""
    return _zh_translations.copy()
